FROM debian:12
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y ca-certificates wget unzip openjdk-17-jre-headless fuse libfuse2 kmod lsb-release binutils bc gnupg gnupg2 gnupg1 software-properties-common
RUN mkdir app
COPY --chmod=744 /entry.sh /app
COPY --chmod=744 /test-portables.sh /app
COPY --chmod=744 /test-deb.sh /app

RUN mkdir -p /scripts/web  \
    /usr/share/data \
    /usr/share/ton/smartcont \
    /var/ton-work/db/static \
    /var/ton-work/db/keyring \
    /var/ton-work/db/import \
    /var/ton-work/logs

COPY --chmod=744 genesis/scripts/start-genesis.sh /scripts
COPY --chmod=744 genesis/scripts/start-validator.sh /scripts
COPY --chmod=744 genesis/scripts/start-node.sh /scripts
COPY genesis/scripts/gen-zerostate.fif /usr/share/data

COPY genesis/scripts/ton-private-testnet.config.json.template /usr/share/data
COPY genesis/scripts/example.config.json /usr/share/data
COPY genesis/scripts/control.template /usr/share/data
COPY genesis/scripts/liteserver /usr/share/data
COPY genesis/scripts/liteserver.pub /usr/share/data

WORKDIR "/app"
ENTRYPOINT ["/app/entry.sh"]