FROM debian:12
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget unzip fuse libfuse2 kmod lsb-release binutils
RUN wget https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb && \
    sudo dpkg -i jdk-21_linux-x64_bin.deb && \
    java -version
RUN mkdir app
COPY --chmod=744 /entry.sh /app
WORKDIR "/app"
ENTRYPOINT ["/app/entry.sh"]

#ok