FROM debian:12
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget unzip openjdk-21-jdk fuse libfuse2 kmod lsb-release binutils
RUN mkdir app
COPY --chmod=744 /entry.sh /app
WORKDIR "/app"
ENTRYPOINT ["/app/entry.sh"]

#ok