FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install --no-install-recommends -y build-essential wget unzip openjdk-21-jre-headless fuse libfuse2 kmod lsb-release binutils
RUN mkdir app
COPY --chmod=744 /entry.sh /app
COPY --chmod=744 test-ton-libs.jar /app
COPY --chmod=744 MyLocalTon.jar /app
COPY --chmod=744 ton-linux-x86_64.zip /app

WORKDIR "/app"
ENTRYPOINT ["/app/entry.sh"]

#ok