FROM centos:centos8

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum install -y wget binutils unzip fuse fuse-devel java-17-openjdk-headless bc

RUN mkdir app
COPY --chmod=744 /entry.sh /app
COPY --chmod=744 /test-portables.sh /app

RUN mkdir -p /scripts/web  \
    /usr/share/data \
    /usr/share/ton/smartcont \
    /var/ton-work/db/static \
    /var/ton-work/db/keyring \
    /var/ton-work/db/import \
    /var/ton-work/logs

COPY --chmod=744 genesis/scripts/start-genesis.sh /scripts
COPY --chmod=744 genesis/scripts/start-validator.sh /scripts
COPY --chmod=744 genesis/scripts/start-node.sh /scripts
COPY genesis/scripts/gen-zerostate.fif /usr/share/data

COPY genesis/scripts/ton-private-testnet.config.json.template /usr/share/data
COPY genesis/scripts/example.config.json /usr/share/data
COPY genesis/scripts/control.template /usr/share/data
COPY genesis/scripts/liteserver /usr/share/data
COPY genesis/scripts/liteserver.pub /usr/share/data

WORKDIR "/app"
ENTRYPOINT ["/app/entry.sh"]

#dht-server: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by dht-server)
