FROM redhat/ubi8
RUN yum install -y wget binutils unzip fuse fuse-devel java-17-openjdk-headless bc && dnf install -y redhat-lsb-core
RUN mkdir app
COPY --chmod=744 /entry.sh /app

RUN mkdir -p /scripts/web  \
    /usr/share/data \
    /usr/share/ton/smartcont \
    /var/ton-work/db/static \
    /var/ton-work/db/keyring \
    /var/ton-work/db/import \
    /var/ton-work/logs

COPY --chmod=744 genesis/scripts/start-genesis.sh /scripts
COPY --chmod=744 genesis/scripts/start-validator.sh /scripts
COPY --chmod=744 genesis/scripts/start-node.sh /scripts
COPY genesis/scripts/gen-zerostate.fif /usr/share/data
COPY genesis/scripts/ton-private-testnet.config.json.template /var/ton-work/db
COPY genesis/scripts/example.config.json /var/ton-work/db
COPY genesis/scripts/control.template /var/ton-work/db
COPY genesis/scripts/liteserver /var/ton-work/db
COPY genesis/scripts/liteserver.pub /var/ton-work/db

WORKDIR "/app"
ENTRYPOINT ["/app/entry.sh"]

# libs ok
# binaries
#                               dht-server: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by dht-server)
#2025-01-09T20:45:02.628133157Z dht-server: /lib64/libpthread.so.0: version `GLIBC_2.30' not found (required by dht-server)
#2025-01-09T20:45:02.628140967Z dht-server: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by dht-server)
#2025-01-09T20:45:02.628144437Z dht-server: /lib64/libc.so.6: version `GLIBC_2.30' not found (required by dht-server)
#2025-01-09T20:45:02.628164027Z dht-server: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by dht-server)