FROM rebornos/rebornos:latest
RUN yes | pacman-key --init && pacman-key --populate archlinux && yes | pacman -Syu wget binutils unzip fuse jre17-openjdk
RUN mkdir /app
COPY --chmod=744 /entry.sh /app
WORKDIR "/app"
ENTRYPOINT ["/app/entry.sh"]

# libs ok
