FROM ubuntu:22.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget unzip openjdk-17-jre-headless fuse libfuse2 kmod lsb-release binutils bc
RUN mkdir app
COPY --chmod=744 /entry.sh /app
COPY --chmod=744 /test-portables.sh /app
COPY --chmod=744 /test-deb.sh /app

RUN mkdir -p /scripts/web  \
    /usr/share/data \
    /usr/share/ton/smartcont \
    /var/ton-work/db/static \
    /var/ton-work/db/keyring \
    /var/ton-work/db/import \
    /var/ton-work/logs

COPY --chmod=744 genesis/scripts/start-genesis.sh /scripts
COPY --chmod=744 genesis/scripts/start-validator.sh /scripts
COPY --chmod=744 genesis/scripts/start-node.sh /scripts
COPY genesis/scripts/gen-zerostate.fif /usr/share/data
COPY genesis/scripts/ton-private-testnet.config.json.template /var/ton-work/db
COPY genesis/scripts/example.config.json /var/ton-work/db
COPY genesis/scripts/control.template /var/ton-work/db
COPY genesis/scripts/liteserver /var/ton-work/db
COPY genesis/scripts/liteserver.pub /var/ton-work/db

WORKDIR "/app"
ENTRYPOINT ["/app/entry.sh"]