FROM linuxmintd/mint20-amd64:latest
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget unzip openjdk-17-jre-headless fuse libfuse2 kmod lsb-release binutils bc
#RUN apt install -y manpages-dev software-properties-common && add-apt-repository -y ppa:ubuntu-toolchain-r/test && apt update && apt install -y gcc-11 g++-11

RUN mkdir app
COPY --chmod=744 /entry.sh /app

RUN mkdir -p /scripts/web  \
    /usr/share/data \
    /var/ton-work/db/static \
    /var/ton-work/db/keyring \
    /var/ton-work/db/import \
    /var/ton-work/logs

COPY --chmod=744 genesis/scripts/start-genesis.sh /scripts
COPY --chmod=744 genesis/scripts/start-validator.sh /scripts
COPY --chmod=744 genesis/scripts/start-node.sh /scripts
COPY genesis/scripts/gen-zerostate.fif /usr/share/ton/smartcont/gen-zerostate.fif
COPY genesis/scripts/ton-private-testnet.config.json.template /var/ton-work/db
COPY genesis/scripts/example.config.json /var/ton-work/db
COPY genesis/scripts/control.template /var/ton-work/db
COPY genesis/scripts/liteserver /var/ton-work/db
COPY genesis/scripts/liteserver.pub /var/ton-work/db

WORKDIR "/app"
ENTRYPOINT ["/app/entry.sh"]

#ok