name: Test TON portable binaries

on: [push,workflow_dispatch,workflow_call]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        docker-file: [dockerfile-ubuntu-20, dockerfile-ubuntu-22, dockerfile-ubuntu-24, dockerfile-debian-11, dockerfile-debian-12,dockerfile-mint-21]
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:v0.11.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts and test utilities
        run: |
          sudo apt install fuse libfuse2
          wget --no-check-certificate -q https://github.com/neodix42/test-ton-libs/releases/latest/download/test-ton-libs.jar
          echo downloaded test-ton-libs          
          wget --no-check-certificate -q http://89.39.107.48:8000/MyLocalTon1.jar -O MyLocalTon.jar
          echo downloaded MyLocalTon
          wget --no-check-certificate -q https://github.com/neodix42/ton/releases/latest/download/ton-linux-x86_64.zip
          echo downloaded ton-appimages
          ls -larth

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          load: true
          push: false
          context: ./
          file: ./${{ matrix.docker-file }}
          tags: ${{ matrix.docker-file }}

      - name: Show images
        run: docker images

      - name: Run
        run: docker run --privileged --cap-add=ALL ${{ matrix.docker-file }}
